# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.idea*
      - id: check-added-large-files
        args: ["--maxkb=100000"]
      - id: no-commit-to-branch
        args: [--branch, main]

  # - repo: local
  #   hooks:
  #     - id: php-fix
  #       name: PHP Fix
  #       entry: phpcbf . --ignore=vendor/ --standard=PSR12
  #       language: system
  #       types: [php]

  # - repo: local
  #   hooks:
  #     - id: php-syntax-check
  #       name: PHP Syntax Check
  #       entry: phpcs . --ignore=vendor/ --standard=PSR12
  #       language: system
  #       types: [php]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0" # Use the sha / tag you want to point at
    hooks:
      - id: prettier

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-java
  #   rev: 1.3.10
  #   hooks:
  #     - id: validate-html

  # - repo: https://github.com/pre-commit/mirrors-csslint
  #   rev: v1.0.5
  #   hooks:
  #     - id: csslint
  #       files: '\.css$'
